hard_tabs = false
tab_spaces = 4
reorder_imports = true
newline_style = "Unix"
max_width= 110
edition = "2021"
use_small_heuristics = "Max"                                                                                 
